[package]
name = "cpo"
version = "0.1.0"
authors = ["Hugo van de Kuilen from Hugo4IT.com <hugo.vandekuilen1234567890@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"